### PR TITLE
Bugfix/remove bitters

### PR DESCRIPTION
**Pull request by beatface**
Removing Bitters (was causing dependency version issues around Bourbon).

### CODE REVIEW

**Comment by bval** [comment]
@beatface But we use bitters...

**Comment by beatface** [comment]
@bval Similar thing here. Bitters is dependent on the latest version of Bourbon (it's pulling in Bourbon 5.0.0.beta.7), however, as per speaking with @jimmythorn, a lot of features are being deprecated in Bourbon 5, so we don't want that. After running into those version issues and speaking with the guys, consensus was that Bitters is not consistently being used by Jimmy and Zach, so we decided to take it out.

**Comment by bval** [comment]
@beatface I'd love to know what @jimmythorn and @zkellerdevelops are using, because the skeleton SASS files that Playbook uses are just bitters and AFAIK we're still using that everywhere...

If we don't want to pull in bourbon 5 yet, a better solution might be to pin the version constraint on bitters to a version that doesn't require bourbon 5...

**Comment by beatface** [comment]
@bval Solution proposal: I'll work to add Bitters back optionally and separate from the Bourbon/Neat option to please everyone. Yeah? @jimmythorn and @zkellerdevelops both said they write their own base styles.

**Pull request merged**
