### PR TITLE
Pull out Spork.

### PR DESCRIPTION
**Pull request by beatface**

### CODE REVIEW

**Comment by bval** [comment]
@beatface Curious why pull out spork? Planning to switch to zeus?

**Comment by beatface** [comment]
@bval Spork isn't up-to-date for Rails 5. I spoke with the guys and they said they haven't used it recently — consensus was to just rip it out. If there's an alternative that makes sense to move to, I'm happy to implement.

**Comment by bval** [comment]
@beatface [zeus](https://github.com/burke/zeus) would be a good alternative if spork isn't being maintained. It's very handy to have Rails and the gemset resident in memory once and let other processes make a quick copy of it rather than having Rails boot up every single time you need a new process. It makes a real difference in development speed, especially if you're doing red/green/refactor development.

**Comment by beatface** [comment]
@bval 👍  Sounds good!

**Pull request merged**
